# Server
server:
  port: 3535

spring:
  # SQL Database (H2)
  datasource:
    url: jdbc:h2:mem:data-db
    driverClassName: org.h2.Driver
    username: admin
    password: 12345

  # JPA and Hibernate
  jpa:
    hibernate:
      ddl-auto: update # disabled because of database initializing
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true

  # H2 Database
  h2:
    console:
      enabled: true
      path: /h2

  # Message Broker (Kafka)
  kafka:
    bootstrap-servers: localhost:9092
    group-id: calculator-group
    topic:
      calculation: calculation

  # Database Initializing
  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

# Logging
logging:
  level:
    root: info
    tr.unvercanunlu.calculator_kafka_producer_consumer.kafka: debug
    tr.unvercanunlu.calculator_kafka_producer_consumer.controller: trace

# API Documentation (OpenAPI)
springdoc:
  swagger-ui:
    path: /api-doc
